env:
    - GHCVER=7.10.2 TEST_PART=CORE1
    - GHCVER=7.10.2 TEST_PART=CORE2
    - GHCVER=7.10.2 TEST_PART=PROFILING
    - GHCVER=7.10.2 TEST_PART=GHCJS

before_install:
    - export GHCJS_BOOTING=1
    - export GHCJS_BOOTING_STAGE1=1
    - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
    - curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
    - travis_retry sudo apt-get update -qq
    - travis_retry sudo apt-get build-dep ghc
    - travis_retry sudo apt-get install nodejs cabal-install-1.22 ghc-$GHCVER alex-3.1.4 happy-1.19.5
    - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/1.22/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH

install:
    - travis_retry cabal update
    - cabal install --only-dependencies --enable-tests --enable-benchmarks
    - cabal install --enable-tests --enable-benchmarks -v -j1 --ghc-options="+RTS -c -RTS"
    - ghcjs --version
    - ghcjs-boot --version
    - ./test/runTravis.sh boot
    - ghcjs-pkg list

script:
    - ./test/runTravis.sh test

notifications:
  irc:
    channels: "irc.freenode.net#ghcjs"
    skip_join: true
  email: true
